### ISSUE TITLE
Dataset structure

### ISSUE THREAD

**Issue by sovit-123** [Vijayabhaskar96/Object-Detection-Algorithms#1]
Hello. This is very helpful for me. But may I know how the dataset directory is structured and how the text files are containing (like 2007_train.txt).

**Comment by Vijayabhaskar96** [comment]
You can download the dataset from here: https://www.kaggle.com/vijayabhaskar96/pascal-voc-2007-and-2012
Extract it wherever you want, just copy paste the path (BASE_PATH) in the configs.py file.

**Comment by sovit-123** [comment]
Thanks a lot. This is very helpful.
